BlockNesting:
  Max: 5

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

SuppressedException:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false
  