inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
    - "Gemfile*"
    - "spec/**/*.rb"

  DisplayCopNames: true
  TargetRubyVersion: 2.6

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/MutableConstant:
  Enabled: false