apiVersion: v1
kind: Service
metadata:
  name: rails
  namespace: chatc3
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
  selector:
    app: rails
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  namespace: chatc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - image: chatc3-backend-rails:latest
        name: rails
        env:
          - name: TZ
            value: Asia/Tokyo
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: rails-secret
                key: mysqlhost
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: rails-secret
                key: mysqluser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rails-secret
                key: mysqlpassword
          - name: ALLOWED_REQUEST_ORIGINS
            valueFrom:
              secretKeyRef:
                name: rails-secret
                key: allowedrequestorigins
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: rails-env
        ports:
        - containerPort: 3000
          name: rails
        volumeMounts:
        - name: rails-persistent-storage
          mountPath: /webapp/public/uploads/user
        command:
        - sh
        - -c
        - "bundle exec rails db:create RAILS_ENV=production \
          && bundle exec rails db:migrate RAILS_ENV=production \
          && bundle exec rails server -e production" 
      volumes:
      - name: rails-persistent-storage
        persistentVolumeClaim:
          claimName: rails-pv-claim 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-env
  namespace: chatc3
data:
  RAILS_ROOT: /webapp
