apiVersion: v1
kind: Service
metadata:
  name: rails
  namespace: chatc3
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
  selector:
    app: rails
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  namespace: chatc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - image: chatc3-backend-rails:latest
        name: rails
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: rails-env
        ports:
        - containerPort: 3000
          name: rails
        volumeMounts:
        - name: rails-persistent-storage
          mountPath: /webapp/public/uploads/user
        command:
        - sh
        - -c
        - "bundle exec rails db:create RAILS_ENV=production \
          && bundle exec rails db:migrate \
          && bundle exec rails server -e production" 
      volumes:
      - name: rails-persistent-storage
        persistentVolumeClaim:
          claimName: rails-pv-claim 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-env
  namespace: chatc3
data:
  MYSQL_HOST: mysql
  MYSQL_USER: root
  MYSQL_PASSWORD: rails
  RAILS_ROOT: /webapp
  ALLOWED_REQUEST_ORIGINS: https://chatc3.net:32115
