kind: PersistentVolume
apiVersion: v1
metadata:
  name: rails-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kubernetes/ChatC3_pv/rails_pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
