apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: chatc3
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: chatc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: chatc3-frontend-nginx:latest
        name: nginx
        imagePullPolicy: Never
        env:
          - name: TZ
            value: Asia/Tokyo
        envFrom:
        - configMapRef:
            name: nginx-env
        ports:
        - containerPort: 80
          name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env
  namespace: chatc3
data:
  VUE_APP_TEST: "chatc3.net"
