apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: chatc3
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: chatc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: chatc3-frontend-nginx:latest
        name: nginx
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: nginx-env
        ports:
        - containerPort: 80
          name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env
  namespace: chatc3
data:
  APISERVER_HOST: "nginx"
  APISERVER_PORT: "8080"
